USE DATABASE SHOPSPHERE_DB;
-- Query 1
SELECT * FROM SCHEMA_MART.MART_REGIONAL_PERFORMANCE;

-- Query 2
SELECT * FROM SCHEMA_MART.MART_PRODUCT_PERFORMANCE;

-- Query 3
SELECT * FROM SCHEMA_MART.MART_DISCOUNT_IMPACT;

-- Query 4
SELECT * FROM SCHEMA_MART.MART_CUSTOMER_SEGMENTS;

-- Query 5
SELECT * FROM SCHEMA_MART.MART_RETENTION_METRICS;